services:
  koinsight:
    build: .
    container_name: koinsight
    ports:
      - "3005:3000"
    volumes:
      - ./.docker-data:/app/data
      - ./books:/app/books
      - ./.env:/app/.env
    environment:
      - BOOKS_PATH=/app/books
    restart: unless-stopped
